// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamWorkload.API.Data;

#nullable disable

namespace TeamWorkload.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416013413_AddTaskStatusHistory")]
    partial class AddTaskStatusHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeamWorkload.API.Models.TaskChangeRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentAssignedMemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CurrentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentEstimatedEffortHours")
                        .HasColumnType("int");

                    b.Property<int?>("NewAssignedMemberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NewDueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NewEstimatedEffortHours")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedById")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentAssignedMemberId");

                    b.HasIndex("NewAssignedMemberId");

                    b.HasIndex("RequestedById");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskChangeRequests", (string)null);
                });

            modelBuilder.Entity("TeamWorkload.API.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssignedMemberId")
                        .HasColumnType("int");

                    b.Property<int>("Complexity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EstimatedEffortHours")
                        .HasColumnType("int");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AssignedMemberId");

                    b.HasIndex("CreatedById");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("TeamWorkload.API.Models.TaskStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangedById")
                        .HasColumnType("int");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<int>("OldStatus")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskStatusHistories", (string)null);
                });

            modelBuilder.Entity("TeamWorkload.API.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("TeamWorkload.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("TeamWorkload.API.Models.TaskChangeRequest", b =>
                {
                    b.HasOne("TeamWorkload.API.Models.User", "CurrentAssignedMember")
                        .WithMany()
                        .HasForeignKey("CurrentAssignedMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TeamWorkload.API.Models.User", "NewAssignedMember")
                        .WithMany()
                        .HasForeignKey("NewAssignedMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TeamWorkload.API.Models.User", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TeamWorkload.API.Models.User", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TeamWorkload.API.Models.TaskItem", "Task")
                        .WithMany("ChangeRequests")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrentAssignedMember");

                    b.Navigation("NewAssignedMember");

                    b.Navigation("RequestedBy");

                    b.Navigation("ReviewedBy");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TeamWorkload.API.Models.TaskItem", b =>
                {
                    b.HasOne("TeamWorkload.API.Models.User", "AssignedMember")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TeamWorkload.API.Models.User", "CreatedBy")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedMember");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("TeamWorkload.API.Models.TaskStatusHistory", b =>
                {
                    b.HasOne("TeamWorkload.API.Models.User", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TeamWorkload.API.Models.TaskItem", "Task")
                        .WithMany("StatusHistories")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TeamWorkload.API.Models.User", b =>
                {
                    b.HasOne("TeamWorkload.API.Models.Team", "Team")
                        .WithMany("Users")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamWorkload.API.Models.TaskItem", b =>
                {
                    b.Navigation("ChangeRequests");

                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("TeamWorkload.API.Models.Team", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TeamWorkload.API.Models.User", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("CreatedTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
